# Generated by Django 3.2.21 on 2023-10-04 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion_tareas', '0003_auto_20231004_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesion',
            name='convocatoria',
            field=models.CharField(default='Ordinaria', max_length=200),
        ),
    ]
