# Generated by Django 3.2.21 on 2023-10-05 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion_tareas', '0004_alter_sesion_convocatoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesion',
            name='numero_sesion',
            field=models.IntegerField(),
        ),
    ]
